# Generated by Django 3.1.6 on 2021-02-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='введите название Категория', max_length=100, verbose_name='Название Категории')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500, null=True, verbose_name='Картинка')),
                ('title', models.CharField(help_text='введите название блюда', max_length=100, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('categories', models.ManyToManyField(to='shop.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
